### ISSUE TITLE
TUsimple labelling tool

### ISSUE THREAD

**Issue by pmharikrishnan** [fabvio/TuSimple-lane-classes#4]
@ fabvio. This is Harikrishnan from India, PhD student. I am working on Indian road lane detection. I would like to know about the tool that u have created

**Comment by Mohamad-Asif-Pir** [comment]
@ fabvio. This is Asif from India, PhD student. I am working on Indian road lane detection. I would like to know about the tool that u have created

**Comment by fabvio** [comment]
Hi guys, the tool is super old and won't be released because I don't even know where to look for it right now. But it was literally maybe 150 python code lines, and I did it in 2 hours. It wouldn't be too difficult to code it, right? You can do that and propose a pull request for other people to use.

I remember it worked like this:
1. Crawl an image from the tusimple dataset
2. Crawl all the lane information
3. Show one of the lanes
4. Ask for a prompt (digit) each one associated to one of the classes of the dataset
5. Continue until all lanes are labelled, then change image
